### ISSUE TITLE
Feed and Conditions

### ISSUE THREAD

**Issue by AxelBriche** [abdeltiflouardi/RssBundle#1]
Hello, please, this exemple it's possible ?

Exemple: 

if($NewsVisibility == 1)
{
    // Include news in feed.
}
elseif($NewsVisibility == 0)
{
    // Don't include news in feed
}

Thanks

**Comment by AxelBriche** [comment]
OR :

os_rss:
    item:
        entity: KynarethNewsBundle:News
        title: titre
        description: contenu
        pubDate: date
        where: visibility == 1

Look "where: visibility == 1", possible please ?

**Comment by abdeltiflouardi** [comment]
+1

**Comment by abdeltiflouardi** [comment]
Done https://github.com/ouardisoft/RssBundle/blob/6d24d5c255c912ca998cb9e72f3a5c5077ef6ab8/Resources/doc/index.md

**Comment by AxelBriche** [comment]
Hello, Thanks! :)
